version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./wordpress_persistence:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql_persistence:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
